# Generated by Django 5.1.4 on 2024-12-15 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=100, verbose_name="Действие, которое надо сделать"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="Время, когда необходимо выполнить привычку",
                    ),
                ),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Периодичность выполнения, в днях"
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Время на выполнение, в секундах"
                    ),
                ),
                (
                    "is_good",
                    models.BooleanField(
                        default=False, verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение за выполнение",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
                "ordering": ("pk",),
            },
        ),
    ]
